### ISSUE TITLE
Distributed training for ImageNet

### ISSUE THREAD

**Issue by charmeleonz** [sunshangquan/logit-standardization-KD#1]
Hi, may I know if your ImageNet experiments ran on multiple GPUS, and if multiple-GPU training is supported? Thanks.

**Comment by sunshangquan** [comment]
For fair comparison, we follow the training setting like DKD on single GPU, and multi-GPU training is not supported yet. Thanks for your attention.

**Comment by charmeleonz** [comment]
Thank you for your response.
